name: Manhunt
main: me.gaagjescraft.network.team.manhunt.Manhunt
version: 1.2.0
description: Twisted Manhunt plugin.
author: GaagjesCraft Network Team (GCNT)
api-version: 1.16
depend:
  - WorldEdit
softdepend:
  - CociteSupport
  - Vault
  - ViaVersion
  - NametagEdit
  - Multiverse-Core
  - PlaceholderAPI
load: POSTWORLD

commands:
  manhuntstats:
    aliases:
      - stats
  manhunt:
    description: Opens the manhunt game menu / managed the game.
  leave:
    aliases:
      - hub
      - quit
    description: Leave your game.
  compass:
    description: Get the compass.
  rejoin:
    description: Rejoin your previous game.